
server.port=8080

github.token=${GITHUB_TOKEN}

github.base-url=https://api.github.com

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s
spring.main.lazy-initialization=true

# Limit Tomcat Threads
server.tomcat.max-threads=20
server.tomcat.accept-count=10

spring.mvc.async.request-timeout=10s

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html